const Images = [
    {image: require('../assets/banners/11.jpg')},
    {image: require('../assets/banners/22.jpg')},
    {image: require('../assets/banners/33.jpg')},
    {image: require('../assets/banners/44.jpg')},
    {image: require('../assets/banners/55.jpg')},
    {image: require('../assets/banners/66.jpg')},
    {image: require('../assets/banners/77.jpg')},
  ];
  
  export const data = [
    {
      id: '1',
      coordinate: {
        latitude: 22.6293867,
        longitude: 88.4354486,
      },
      title: 'ข้าวกะเพราหมูสับ',
      description: `แนะนำสำหรับคุณ`,
      image: Images[0].image,
      rating: 4,
      reviews: 99,
      categories: ['Restaurant', 'Hotel', 'Dineout'],
    },
    {
      id: '2',
      coordinate: {
        latitude: 22.6345648,
        longitude: 88.4377279,
      },
      title: 'ข้าวผัดรวมมิตร',
      description: `แนะนำสำหรับคุณ`,
      image: Images[1].image,
      rating: 5,
      reviews: 102,
      categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
    },
    {
      id: '3',
      coordinate: {
        latitude: 22.6281662,
        longitude: 88.4410113,
      },
      title: 'ข้าวคลุกกะปิ',
      description: `แนะนำสำหรับคุณ`,
      image: Images[2].image,
      rating: 3,
      reviews: 220,
      categories: ['Restaurant', 'Hotel', 'Dineout'],
    },
    {
      id: '4',
      coordinate: {
        latitude: 22.6341137,
        longitude: 88.4497463,
      },
      title: 'ข้าวเครื่องแกงหมูกรอบ',
      description: `แนะนำสำหรับคุณ`,
      image: Images[3].image,
      rating: 4,
      reviews: 48,
      categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
    },
    {
      id: '5',
      coordinate: {
        latitude: 22.6292757,
        longitude: 88.444781,
      },
      title: 'ข้าวหมูทอดกระเทียม',
      description: `แนะนำสำหรับคุณ`,
      image: Images[4].image,
      rating: 4,
      reviews: 178,
      categories: ['Restaurant', 'Hotel', 'Dineout'],
    },
    {
      id: '6',
      coordinate: {
        latitude: 22.6293867,
        longitude: 88.4354486,
      },
      title: 'ผัดไทย',
      description: `แนะนำสำหรับคุณ`,
      image: Images[0].image,
      rating: 4,
      reviews: 99,
      categories: ['Restaurant', 'Hotel', 'Dineout'],
    },
    {
      id: '7',
      coordinate: {
        latitude: 22.6345648,
        longitude: 88.4377279,
      },
      title: 'ข้าวราดผัดผักบุ้ง',
      description: `แนะนำสำหรับคุณ`,
      image: Images[1].image,
      rating: 5,
      reviews: 102,
      categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
    },
  ];